/**
 * Worker Type Definitions
 * 
 * Types for the FFmpeg worker processing pipeline.
 * 
 * **Validates: Requirements 7.1, 7.2**
 */

/**
 * Result of processing a single bick.
 */
export interface ProcessingResult {
  bickId: string;
  waveformUrl: string;
  ogImageUrl: string;
  teaserUrl: string;
}

/**
 * Result of an FFmpeg command execution.
 */
export interface FFmpegResult {
  stdout: string;
  stderr: string;
  exitCode: number;
}

/**
 * Waveform data structure for client-side rendering.
 * Contains normalized amplitude values (0.0 to 1.0).
 */
export interface WaveformData {
  version: 1;
  sampleRate: number;
  samplesPerSecond: number;
  duration: number;
  peaks: number[];
}

/**
 * Asset types that can be generated by the worker.
 */
export type AssetType = 'original' | 'waveform_json' | 'og_image' | 'teaser_mp4';

/**
 * Asset record to be inserted into bick_assets table.
 */
export interface AssetRecord {
  bick_id: string;
  asset_type: AssetType;
  storage_key: string;
  cdn_url: string;
  mime_type: string;
  size_bytes: number;
}

/**
 * Error types for different failure scenarios.
 */
export enum ProcessingErrorType {
  DOWNLOAD_FAILED = 'DOWNLOAD_FAILED',
  INVALID_AUDIO = 'INVALID_AUDIO',
  FFMPEG_FAILED = 'FFMPEG_FAILED',
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  DATABASE_ERROR = 'DATABASE_ERROR',
}

/**
 * Custom error class for processing failures.
 */
export class ProcessingError extends Error {
  constructor(
    public readonly type: ProcessingErrorType,
    message: string,
    public readonly bickId?: string,
    public readonly step?: string,
    public readonly cause?: Error
  ) {
    super(message);
    this.name = 'ProcessingError';
  }
}
